### ISSUE TITLE
Sessão 1 - Assistir todos os vídeos e ler os documentos incluídos para download  | PRAZO 20/03

### ISSUE THREAD

**Issue by joaovinicius** [NeroTsk/Curso#1]
Section: 1 - 0 / 22 - How to Get on the web

- [x] 1. About this course what you will learn
- [x] 2. Checklist to becoming a web developer
- [x] 3. Web editors
- [x] 4. Web Servers Local Machines
- [x] 5. Web development web server resources
- [x] 6. web development resource guide
- [x] 7. Planning your Website requirements
- [x] 8. web development and hosting
- [x] 9. Web development hosting and CMS
- [x] 10. Picking and finding the best Domain Names
- [x] 11. Step 1 getting started online
- [x] 12. Step1 - Getting started online
- [x] 13. Getting started online why have a domain
- [x] 14. First Steps to Getting online claim your spot on the internet
- [x] 15. Web file transfer to server FTP apps
- [x] 16. Web development FTP software list
- [x] 17. Web Databases phpmyadmin mySQL
- [x] 18. Version control file sharing Git
- [x] 19. website planning and design
- [x] 20. Web development Course Resources
- [x] 21. Web Developer getting social
- [x] 22. Getting social resources

Obs: Criar uma pasta dentro do diretório chamada "PDF" e colocar todos os pdf baixados dentro, dar commit para cada pdf e subir.
Para cada tarefa feita, selecionar o checkbox.

**Comment by NeroTsk** [comment]
apenas algumas duvidas em relação a parte de hosting do 8º item

**Comment by joaovinicius** [comment]
> apenas algumas duvidas em relação a parte de hosting do 8º item

eu tenho um servidor desses simplizinho, dai te libero um host desses, segue em frente que você vai voltar a essa etapa quando for subir o projeto

**Comment by NeroTsk** [comment]
> > apenas algumas duvidas em relação a parte de hosting do 8º item
> 
> eu tenho um servidor desses simplizinho, dai te libero um host desses, segue em frente que você vai voltar a essa etapa quando for fizer e for subir o projeto

beleza continuando então

**Comment by NeroTsk** [comment]
Parte de ftp vou ver com você no servidor também? eu ja usei algumas vezes para passar jogos no ps3 mas não sei se é a mesma ideia kkkkkkkkk

**Comment by joaovinicius** [comment]
> Parte de ftp vou ver com você no servidor também? eu ja usei algumas vezes para passar jogos no ps3 mas não sei se é a mesma ideia kkkkkkkkk

possívelmente seja a mesma coisa, mas vai ver sim, o ftp não é mto utilizado pra desenvolvimento de sistema, na verdade usar ftp não é nem uma boa prática, mas vo te mostrar pra vc ficar sabendo q existe e como funciona
